In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [11]:
import numpy as np 

In [5]:
np.__version__

'1.26.4'

In [7]:
np.add(1,1)

2

In [9]:
a=np.array([1,3,5])

In [11]:
a

array([1, 3, 5])

In [13]:
a.ndim

1

In [15]:
a.shape

(3,)

In [25]:
b=np.array([[1,3,5],[4,6,7]])

In [27]:
b

array([[1, 3, 5],
       [4, 6, 7]])

In [29]:
b.ndim

2

In [31]:
b.shape

(2, 3)

In [33]:
c=np.array([[[1,2,3],[4,5,6,],[7,8,9]]])

In [35]:
c.ndim

3

In [37]:
c.shape

(1, 3, 3)

In [39]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [57]:
d=np.array([[[[[1,2,3],[4,5,6]]]]])

In [59]:
d

array([[[[[1, 2, 3],
          [4, 5, 6]]]]])

In [61]:
d.shape

(1, 1, 1, 2, 3)

In [55]:
d.ndim

4

In [102]:
a1=np.array([[1,2,3,9,5],[6,7,8,9,10]])

In [104]:
a1

array([[ 1,  2,  3,  9,  5],
       [ 6,  7,  8,  9, 10]])

In [106]:
a1[1,1]

7

In [110]:
a1[0,3]

9

In [128]:
a2=np.array([[[1,3,5,9,7],[2,4,5,3,6],[3,9,1,3,5]]])

In [130]:
a2[0,2,1]

9

In [134]:
a3=np.array([[[1,3,5],[4,6,7]],[[0,6,8],[8,9,5]]])

In [138]:
a3

array([[[1, 3, 5],
        [4, 6, 7]],

       [[0, 6, 8],
        [8, 9, 5]]])

In [140]:
a3[0,1,2]

7

In [142]:
a3[1,0,1]

6

In [144]:
a4=np.array([[[1,3,5],[4,6,7]],[[0,6,8],[8,9,5]]])

In [146]:
a3[1,0,0]

0

In [148]:
a4=np.array([1,2,3,4,5])

In [150]:
a4[2::]

array([3, 4, 5])

In [152]:
a4[::-1]

array([5, 4, 3, 2, 1])

In [13]:
aa=np.array([1,2,3,4,5,6,7,8,9,10])

In [184]:
a5[::3]

array([ 1,  4,  7, 10])

In [192]:
a5[:3:2]

array([1, 3])

In [194]:
print(type(a5))

<class 'numpy.ndarray'>


In [196]:
print(a5.dtype)

int32


In [15]:
ab= aa.astype(float)
ab

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [17]:
ba=np.array(["ak","dj","sn"])
ba

array(['ak', 'dj', 'sn'], dtype='<U2')

In [19]:
print(ba.dtype)

<U2


In [29]:
a6=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
a7=a6.reshape(4,3)

In [37]:
a7

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
#Flatning

In [39]:
a_one=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [41]:
a_one

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [45]:
a_new=a_one.reshape(-1)
print(a_new)

[ 1  2  3  4  5  6  7  8  9 10]


In [53]:
a_two=np.array([1,2,3,4,5,6,7,8,9,10])
for i in a_two:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [61]:
a_three=np.array([[1,2,3],[4,5,6]])
for d in a_three:
    for j in d:
        print(j)

1
2
3
4
5
6


In [67]:
a_four=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in a_four:
    for j in i:
        for l in j:
            print(l)

1
2
3
4
5
6
7
8
9


In [71]:
a_five=np.zeros((2,2))
a_five

array([[0., 0.],
       [0., 0.]])

In [75]:
a_six=np.ones((2,2))
a_six

array([[1., 1.],
       [1., 1.]])

In [85]:
from numpy import random
x=random.randint(100,size=(6,8))
x

array([[60, 94, 55, 27, 76, 81, 40,  2],
       [67, 60, 11, 57, 55, 80, 17, 41],
       [45, 78, 29, 53, 25, 60, 96, 57],
       [30, 19, 24, 17, 60,  4, 60, 98],
       [ 4, 93, 56, 20, 46, 61, 15, 21],
       [51, 73, 32,  6, 42, 98, 41, 55]])

In [91]:
y=random.choice([5,6,3,4,9],size=(3,4))
y

array([[9, 3, 3, 6],
       [4, 6, 9, 5],
       [9, 5, 5, 9]])

In [95]:
y=random.choice([1,2,3,4,5],size=(2,5))
y

array([[4, 5, 1, 2, 1],
       [2, 3, 4, 1, 2]])

In [97]:
s=np.array([[[1,1,1],[1,1,1],[1,1,1]]])
s

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [115]:
s=random.choice([1],size=(1,3,3))
s

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [135]:
s=np.array([[1,2,3],[2,3,4]])
b=s.reshape(-1)
print(b[::2])

[1 3 3]


In [ ]:
#Write a numpy program to swap rows and columns of a given array in reverse order


In [1]:
import pandas as pd
